# Generated by Django 3.1.6 on 2021-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='doorphone_pay',
            field=models.FloatField(default=None, verbose_name='Домофон'),
        ),
    ]
