# Generated by Django 3.1.6 on 2021-02-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility_bills', '0004_auto_20210214_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['date_create'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
